version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT}:80"
    environment:
      - NODE_ENV=production
    networks:
      - my-network

networks:
  my-network:
    external: true
